* [33m9808bc4[m[33m ([m[1;36mHEAD[m[33m -> [m[1;32mmaster[m[33m, [m[1;31morigin/master[m[33m, [m[1;31morigin/HEAD[m[33m)[m Stop tracking application.properties
* [33m4d73268[m Stop tracking application.properties
* [33mea0b99f[m Multiple components added, along with the design change and maps, scrolling part added
* [33me1fc90e[m added some stylings in this, some styling needs to be discussed.
* [33mafd2cc2[m Typescript migration done.
* [33m4fcc28b[m README file added, after a certain point when i felt it can be created
* [33mbef495a[m Multiple images display added in the inventory view for the admin
* [33mac5ab51[m Multiple images of bikes feature added
* [33mb49deac[m Mobile app code made modular
* [33m7edc3ea[m Mobile App configured
* [33m4cb0cb3[m Initial-commit for Shree ganesh autodeal
