package com.autodeal.ShreeGaneshAutodeal.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;
import static org.mockito.ArgumentMatchers.any;
import static org.mockito.Mockito.verify;
import static org.mockito.Mockito.when;

import com.autodeal.ShreeGaneshAutodeal.domain.Category;
import com.autodeal.ShreeGaneshAutodeal.dto.CategoryRequest;
import com.autodeal.ShreeGaneshAutodeal.dto.CategoryResponse;
import com.autodeal.ShreeGaneshAutodeal.repository.CategoryRepository;
import jakarta.persistence.EntityNotFoundException;
import java.util.List;
import java.util.Optional;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.extension.ExtendWith;
import org.mockito.InjectMocks;
import org.mockito.Mock;
import org.mockito.junit.jupiter.MockitoExtension;
import org.springframework.data.domain.Sort;

@ExtendWith(MockitoExtension.class)
class CategoryServiceTest {

	@Mock
	private CategoryRepository categoryRepository;

	@InjectMocks
	private CategoryService categoryService;

	private Category createCategory(Long id, String name, String slug, String description) {
		Category category = new Category();
		category.setId(id);
		category.setName(name);
		category.setSlug(slug);
		category.setDescription(description);
		return category;
	}

	@Nested
	@DisplayName("findAll Tests")
	class FindAllTests {

		@Test
		@DisplayName("Should return sorted category response list")
		void shouldReturnSortedCategoryResponseList() {
			Category cat1 = createCategory(1L, "Cruiser", "cruiser", "Cruiser bikes");
			Category cat2 = createCategory(2L, "Scooter", "scooter", "Automatic scooters");
			when(categoryRepository.findAll(Sort.by("name"))).thenReturn(List.of(cat1, cat2));

			List<CategoryResponse> result = categoryService.findAll();

			assertThat(result).hasSize(2);
			assertThat(result.get(0).id()).isEqualTo(1L);
			assertThat(result.get(0).name()).isEqualTo("Cruiser");
			assertThat(result.get(0).slug()).isEqualTo("cruiser");
			assertThat(result.get(1).id()).isEqualTo(2L);
			assertThat(result.get(1).name()).isEqualTo("Scooter");
			verify(categoryRepository).findAll(Sort.by("name"));
		}

		@Test
		@DisplayName("Should return empty list when no categories exist")
		void shouldReturnEmptyListWhenNoCategoriesExist() {
			when(categoryRepository.findAll(Sort.by("name"))).thenReturn(List.of());

			List<CategoryResponse> result = categoryService.findAll();

			assertThat(result).isEmpty();
			verify(categoryRepository).findAll(Sort.by("name"));
		}
	}

	@Nested
	@DisplayName("getEntity Tests")
	class GetEntityTests {

		@Test
		@DisplayName("Should return category entity when found")
		void shouldReturnCategoryWhenFound() {
			Category category = createCategory(1L, "Sports", "sports", "Sports bikes");
			when(categoryRepository.findById(1L)).thenReturn(Optional.of(category));

			Category result = categoryService.getEntity(1L);

			assertThat(result).isNotNull();
			assertThat(result.getId()).isEqualTo(1L);
			assertThat(result.getName()).isEqualTo("Sports");
			verify(categoryRepository).findById(1L);
		}

		@Test
		@DisplayName("Should throw EntityNotFoundException when category not found")
		void shouldThrowExceptionWhenNotFound() {
			when(categoryRepository.findById(99L)).thenReturn(Optional.empty());

			assertThatThrownBy(() -> categoryService.getEntity(99L))
					.isInstanceOf(EntityNotFoundException.class)
					.hasMessageContaining("Category not found: 99");

			verify(categoryRepository).findById(99L);
		}
	}

	@Nested
	@DisplayName("create Tests")
	class CreateTests {

		@Test
		@DisplayName("Should create category successfully with auto-generated slug")
		void shouldCreateCategoryWithAutoGeneratedSlug() {
			CategoryRequest request = new CategoryRequest("Super Sports", null, "High power bikes");

			when(categoryRepository.existsByNameIgnoreCase("Super Sports")).thenReturn(false);
			when(categoryRepository.existsBySlug("super-sports")).thenReturn(false);
			when(categoryRepository.save(any(Category.class))).thenAnswer(invocation -> {
				Category saved = invocation.getArgument(0);
				saved.setId(10L);
				return saved;
			});

			CategoryResponse response = categoryService.create(request);

			assertThat(response).isNotNull();
			assertThat(response.id()).isEqualTo(10L);
			assertThat(response.name()).isEqualTo("Super Sports");
			assertThat(response.slug()).isEqualTo("super-sports");
			assertThat(response.description()).isEqualTo("High power bikes");
			verify(categoryRepository).save(any(Category.class));
		}

		@Test
		@DisplayName("Should create category with custom slug")
		void shouldCreateCategoryWithCustomSlug() {
			CategoryRequest request = new CategoryRequest("Commuter", "daily-commute", "Economical bikes");

			when(categoryRepository.existsByNameIgnoreCase("Commuter")).thenReturn(false);
			when(categoryRepository.existsBySlug("daily-commute")).thenReturn(false);
			when(categoryRepository.save(any(Category.class))).thenAnswer(invocation -> {
				Category saved = invocation.getArgument(0);
				saved.setId(11L);
				return saved;
			});

			CategoryResponse response = categoryService.create(request);

			assertThat(response.slug()).isEqualTo("daily-commute");
			verify(categoryRepository).save(any(Category.class));
		}

		@Test
		@DisplayName("Should throw IllegalArgumentException when name already exists")
		void shouldThrowExceptionWhenNameAlreadyExists() {
			CategoryRequest request = new CategoryRequest("Cruiser", null, "Desc");
			when(categoryRepository.existsByNameIgnoreCase("Cruiser")).thenReturn(true);

			assertThatThrownBy(() -> categoryService.create(request))
					.isInstanceOf(IllegalArgumentException.class)
					.hasMessage("Category name already exists");
		}

		@Test
		@DisplayName("Should throw IllegalArgumentException when slug already exists")
		void shouldThrowExceptionWhenSlugAlreadyExists() {
			CategoryRequest request = new CategoryRequest("Cruiser", "cruiser-bikes", "Desc");
			when(categoryRepository.existsByNameIgnoreCase("Cruiser")).thenReturn(false);
			when(categoryRepository.existsBySlug("cruiser-bikes")).thenReturn(true);

			assertThatThrownBy(() -> categoryService.create(request))
					.isInstanceOf(IllegalArgumentException.class)
					.hasMessage("Category slug already exists");
		}
	}

	@Nested
	@DisplayName("update Tests")
	class UpdateTests {

		@Test
		@DisplayName("Should update category successfully")
		void shouldUpdateCategorySuccessfully() {
			Category existing = createCategory(1L, "Old Name", "old-name", "Old Desc");
			CategoryRequest request = new CategoryRequest("New Name", "new-name", "New Desc");

			when(categoryRepository.findById(1L)).thenReturn(Optional.of(existing));
			when(categoryRepository.findBySlug("new-name")).thenReturn(Optional.empty());

			CategoryResponse response = categoryService.update(1L, request);

			assertThat(response.name()).isEqualTo("New Name");
			assertThat(response.slug()).isEqualTo("new-name");
			assertThat(response.description()).isEqualTo("New Desc");
		}

		@Test
		@DisplayName("Should allow updating category with the same slug on the same entity")
		void shouldAllowUpdateWithSameSlugOnSameEntity() {
			Category existing = createCategory(1L, "Cruiser", "cruiser", "Old Desc");
			CategoryRequest request = new CategoryRequest("Cruiser Updated", "cruiser", "New Desc");

			when(categoryRepository.findById(1L)).thenReturn(Optional.of(existing));
			when(categoryRepository.findBySlug("cruiser")).thenReturn(Optional.of(existing));

			CategoryResponse response = categoryService.update(1L, request);

			assertThat(response.name()).isEqualTo("Cruiser Updated");
			assertThat(response.slug()).isEqualTo("cruiser");
			assertThat(response.description()).isEqualTo("New Desc");
		}

		@Test
		@DisplayName("Should throw IllegalArgumentException when slug belongs to another category")
		void shouldThrowExceptionWhenSlugBelongsToAnotherCategory() {
			Category existing = createCategory(1L, "Cruiser", "cruiser", "Desc");
			Category other = createCategory(2L, "Tourer", "tourer", "Desc");
			CategoryRequest request = new CategoryRequest("Cruiser", "tourer", "Desc");

			when(categoryRepository.findById(1L)).thenReturn(Optional.of(existing));
			when(categoryRepository.findBySlug("tourer")).thenReturn(Optional.of(other));

			assertThatThrownBy(() -> categoryService.update(1L, request))
					.isInstanceOf(IllegalArgumentException.class)
					.hasMessage("Category slug already exists");
		}
	}

	@Nested
	@DisplayName("delete Tests")
	class DeleteTests {

		@Test
		@DisplayName("Should delete existing category")
		void shouldDeleteExistingCategory() {
			Category existing = createCategory(1L, "Cruiser", "cruiser", "Desc");
			when(categoryRepository.findById(1L)).thenReturn(Optional.of(existing));

			categoryService.delete(1L);

			verify(categoryRepository).delete(existing);
		}

		@Test
		@DisplayName("Should throw EntityNotFoundException when deleting non-existent category")
		void shouldThrowExceptionWhenDeletingNonExistentCategory() {
			when(categoryRepository.findById(99L)).thenReturn(Optional.empty());

			assertThatThrownBy(() -> categoryService.delete(99L))
					.isInstanceOf(EntityNotFoundException.class)
					.hasMessageContaining("Category not found: 99");
		}
	}

	@Nested
	@DisplayName("Helper Methods Tests")
	class HelperMethodsTests {

		@Test
		@DisplayName("normalizeSlug should correctly normalize strings")
		void testNormalizeSlug() {
			assertThat(CategoryService.normalizeSlug("Super Bikes 1000cc!"))
					.isEqualTo("super-bikes-1000cc");
			assertThat(CategoryService.normalizeSlug("---Scooter & Moped---"))
					.isEqualTo("scooter-moped");
			assertThat(CategoryService.normalizeSlug("Electric_Vehicle"))
					.isEqualTo("electric-vehicle");
		}

		@Test
		@DisplayName("blankToNull should trim and handle blank strings")
		void testBlankToNull() {
			assertThat(CategoryService.blankToNull(null)).isNull();
			assertThat(CategoryService.blankToNull("")).isNull();
			assertThat(CategoryService.blankToNull("   ")).isNull();
			assertThat(CategoryService.blankToNull("  valid string  ")).isEqualTo("valid string");
		}
	}
}
